# Generated by Django 3.2.16 on 2022-11-15 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del avion')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ciudad', models.CharField(max_length=40, verbose_name='nombre de la ciudad')),
                ('pais', models.CharField(max_length=40, verbose_name='nombre del pais')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destino',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha del vuelo')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.destino')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ciudad', models.CharField(max_length=40, verbose_name='nombre de la ciudad')),
                ('pais', models.CharField(max_length=40, verbose_name='nombre del pais')),
            ],
            options={
                'verbose_name': 'Origen vuelo',
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('capacidad', models.PositiveIntegerField(default=0, verbose_name='capacidad del avion')),
                ('modelo_avion', models.CharField(max_length=20, verbose_name='modelo del avion')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.compania')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.itinerario')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
            },
        ),
        migrations.AddField(
            model_name='itinerario',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.origen'),
        ),
    ]
