# Generated by Django 3.2.16 on 2022-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='fecha',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='hora',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horario del vuelo'),
        ),
    ]
