# Generated by Django 3.2.16 on 2022-11-18 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vuelo', '0002_auto_20221117_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='compania',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='modelo_avion',
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('modelo', models.CharField(max_length=20, verbose_name='modelo del avion')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.compania')),
            ],
            options={
                'verbose_name': 'Avion',
                'verbose_name_plural': 'Aviones',
            },
        ),
        migrations.AddField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vuelo.avion'),
            preserve_default=False,
        ),
    ]
