# Generated by Django 3.2.16 on 2022-11-22 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vuelo', '0003_auto_20221117_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hora', models.IntegerField(blank=True, null=True, verbose_name='Horario del vuelo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itinerario',
            name='descripcion',
            field=models.CharField(default='', max_length=40, verbose_name='descripcion del vuelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='hora',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vuelo.hora'),
            preserve_default=False,
        ),
    ]
