# Generated by Django 3.2.16 on 2022-11-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('ocupation', models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Operador')], max_length=1)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('image', models.ImageField(upload_to='User', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
