# Generated by Django 3.2.16 on 2022-11-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='User', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
