# Generated by Django 3.2.16 on 2022-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha del vuelo'),
        ),
    ]
